### ISSUE TITLE
Sort out the Note field and facet

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#100] opened 2020-04-21 21:47 UTC
### Done when
the following questions have been answered
1. Is one of the Note fields just a copy of Genre? That's was appears to be the case in the same Rebecca gave us.
1. Do we really want to facet on Note field? Seems like there's a chance this could end up being free text, which we would not want to facet on.

**Comment by foglabs-zen** [comment] 2020-04-22 18:49
PSA: The Note field is repeatable and required to be paired with a controlled-vocabulary 'Note Type'.

The Note column with 'Note Type' `general` seems to be a duplicate of Genre in the input data, but there's also a more legit 'Note' column of type 'local'

**Closed** 2020-05-07 16:52 UTC
